(define-constant CONTRACT-OWNER tx-sender)
(define-constant ERR-NOT-AUTHORIZED (err u401))
(define-constant ERR-NOT-WHITELISTED (err u403))
(define-map whitelisted-oracles principal { active: bool, stake: uint, submissions: uint })
(define-public (register-oracle (stake uint))
  (begin
    (try! (stx-transfer? stake tx-sender (as-contract tx-sender)))
    (map-set whitelisted-oracles tx-sender { active: true, stake: stake, submissions: u0 })
    (ok true)))
(define-public (deregister-oracle)
  (let ((info (unwrap! (map-get? whitelisted-oracles tx-sender) ERR-NOT-WHITELISTED)))
    (try! (as-contract (stx-transfer? (get stake info) tx-sender tx-sender)))
    (map-delete whitelisted-oracles tx-sender)
    (ok true)))
(define-read-only (is-whitelisted (oracle principal))
  (match (map-get? whitelisted-oracles oracle)
    info (get active info)
    false))
