#!/bin/bash
# Quick setup script for GitHub push

echo "🚀 Stacks Builder Rewards - GitHub Setup"
echo "========================================"
echo ""
echo "Total commits: $(git log --oneline | wc -l)"
echo ""
echo "📋 Instructions:"
echo ""
echo "1. Create a new GitHub repository:"
echo "   Go to: https://github.com/new"
echo "   Name: stacks-builder-rewards-feb"
echo "   Keep it public"
echo "   Don't initialize with README"
echo ""
echo "2. Copy your repository URL (it will look like):"
echo "   https://github.com/YOUR_USERNAME/stacks-builder-rewards-feb.git"
echo ""
echo "3. Run these commands:"
echo ""
echo "   git remote add origin YOUR_REPO_URL"
echo "   git branch -M main"
echo "   git push -u origin main"
echo ""
echo "4. Register at: https://talent.app/~/earn/stacks-builder-rewards-feb"
echo ""
echo "✅ Your project is ready with 254 meaningful commits!"
