;; Security guard 853
(define-constant CONTRACT-OWNER tx-sender)
(define-constant ERR-NOT-AUTHORIZED (err u401))
(define-data-var paused bool false)
(define-data-var fee-rate uint u250)
(define-data-var min-amount uint u1000000)
(define-data-var contract-owner principal tx-sender)
(define-public (update-fee (new-fee uint))
  (begin (asserts! (is-eq tx-sender CONTRACT-OWNER) ERR-NOT-AUTHORIZED)
    (asserts! (<= new-fee u1000) (err u400))
    (var-set fee-rate new-fee) (ok true)))
